package Kontor::Model::Kontor;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Kontor::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=kontor',
        user => '',
        password => '',
    }
);

=head1 NAME

Kontor::Model::Kontor - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Kontor>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Kontor::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

Kaare Rasmussen

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
