#!/usr/bin/env perl

use strict;
use warnings;

use lib qw(lib);

use Kontor::Schema;

use SQL::Translator;

my $schema = Kontor::Schema->connect('dbi:Pg:dbname=kontor') or die "can't connect to Schema";
my $translator = SQL::Translator->new(
	parser        => 'SQL::Translator::Parser::DBIx::Class',
	parser_args   => { dbic_schema => $schema },
	producer      => 'GraphViz',
	producer_args => {
		out_file		=> 'schema.png',
		output_type		=> 'png',
		title			=> 'Kontor Schema',
	},
) or die SQL::Translator->error;

$translator->translate;
